# Configurações do Spring
spring:
  config:
    import: optional:file:.env[.properties]

  # Cache
  cache:
    type: simple

# Logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.soat.fiap.food.core.payment: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    org.springdoc: DEBUG

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
