spring:

# Tracing Distribuído
management:
  tracing:
    enabled: false

# Configurações de log para testes
logging:
  level:
    root: WARN
    com.fastfood: DEBUG
    org.springframework.test: INFO
    org.hibernate.SQL: DEBUG
