services:
  # Aplicação principal
  payment-ms:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_PORT: ${SERVER_PORT}
    image: foodcore-payment-ms:latest
    container_name: foodcore-payment-ms
    ports:
      - "80:${SERVER_PORT}"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:${SERVER_PORT}/api/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      payment-ms-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - fastfood-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  # Banco de dados PostgreSQL
  payment-ms-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: foodcore-payment-ms-db
    restart: unless-stopped
    mem_limit: 3g
    cpu_count: 2
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}" # Data Explorer UI
      - "10251-10255:10251-10255"
    volumes:
      - payment_ms_cosmosdb_data:/tmp/cosmos/appdata # https://stackoverflow.com/questions/72466963/cosmosdb-emulator-linux-image-mount-volume
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:${DB_PORT}/_explorer/emulator.pem"]
      interval: 3s
      timeout: 5s
      retries: 60
    networks:
      - fastfood-network

networks:
  fastfood-network:
    driver: bridge

volumes:
  payment_ms_cosmosdb_data: