services:
  # Aplicação principal
  payment-ms:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        APP_PORT: ${SERVER_PORT}
    image: foodcore-payment-ms:latest
    container_name: foodcore-payment-ms
    ports:
      - "80:${SERVER_PORT}"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:${SERVER_PORT}/api/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      payment-ms-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - fastfood-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

  # Banco de dados MongoDB
  payment-ms-db:
    image: mongo:7.0
    container_name: foodcore-payment-ms-db
    ports:
      - "${DB_PORT}:27017"
    env_file:
      - .env
    volumes:
      - payment_ms_mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    command: [ "--bind_ip_all" ]
    networks:
      - fastfood-network

networks:
  fastfood-network:
    driver: bridge

volumes:
  payment_ms_mongo_data: